### PR TITLE
easy install and run scripts for windows

### PR DESCRIPTION
**Pull request by egokick**
Added windows-install.bat, windows-run.bat and windows-uninstall.bat scripts to make it easier to run on windows

### CODE REVIEW

**Comment by deepfates** [comment]
is this ready to merge? tbh i do not have a Windows machine to test this but it looks fine i think

**Comment by egokick** [comment]
@deepfates I attached a video of the install script working in windows. I had to downgrade altair in the pyproject.toml file to get it working in windows
`altair = "^4.0.0"`

I didn't include that change in the PR because I don't know if it will impact builds on different operating systems.

The cuda_install.py script isn't fully automated but it does guide windows users through the cuda install and I used it to get cuda working on windows

https://github.com/deepfates/memery/assets/580550/86f3a692-638d-4fe1-8552-ae4bc8cfa185

**Comment by deepfates** [comment]
Okay i don't even know that we're using altair in this project, really need to refactor a bunch of stuff here lol. want to add that change and we'll merge and see if anything breaks?

**Comment by egokick** [comment]
@deepfates  done

**Pull request merged**
